import type { AtlasLayerConfig } from "@/types/atlas";

export const atlasLayers: AtlasLayerConfig[] = [
  // Overview
  {
    id: "area_km2",
    label: "Area",
    group: "overview",
    description: "Municipal area in square kilometres.",
    sourceKey: "identity",
    attributeKey: "areaKm2",
    type: "numeric",
    legendType: "gradient",
    unit: "km²",
    formatter: "km2",
    nullLabel: "No area data",
    enabledInV1: true,
    citation: "CNIG/IGN Líneas de Límites Municipales",
  },
  {
    id: "neighbours_count",
    label: "Neighbours",
    group: "overview",
    description: "Number of directly adjacent municipalities.",
    sourceKey: "derived/neighbours",
    attributeKey: "neighboursCount",
    type: "numeric",
    legendType: "buckets",
    formatter: "integer",
    nullLabel: "No neighbour data",
    enabledInV1: true,
    citation: "Derived from official boundaries",
  },
  // Demography
  {
    id: "population_total",
    label: "Population",
    group: "demography",
    description: "Total registered population (padrón municipal).",
    sourceKey: "population",
    attributeKey: "populationTotal",
    type: "numeric",
    legendType: "gradient",
    formatter: "integer",
    nullLabel: "No population data",
    enabledInV1: false,
    citation: "INE Padrón Municipal",
  },
  {
    id: "density_per_km2",
    label: "Population density",
    group: "demography",
    description: "Residents per square kilometre.",
    sourceKey: "population",
    attributeKey: "densityPerKm2",
    type: "numeric",
    legendType: "gradient",
    unit: "people/km²",
    formatter: "density",
    nullLabel: "No density data",
    enabledInV1: false,
    citation: "INE Padrón Municipal + CNIG area",
  },
  {
    id: "age_median",
    label: "Median age",
    group: "demography",
    description: "Median age of the municipal population.",
    sourceKey: "population",
    attributeKey: "ageMedian",
    type: "numeric",
    legendType: "gradient",
    unit: "years",
    formatter: "integer",
    nullLabel: "No age data",
    enabledInV1: false,
  },
  {
    id: "share_over_65",
    label: "Share aged 65+",
    group: "demography",
    description: "Percentage of population aged 65 and over.",
    sourceKey: "population",
    attributeKey: "shareOver65",
    type: "numeric",
    legendType: "gradient",
    unit: "%",
    formatter: "percentage",
    nullLabel: "No data",
    enabledInV1: false,
  },
  {
    id: "foreign_born_share",
    label: "Foreign-born share",
    group: "demography",
    description: "Percentage of population born outside Spain.",
    sourceKey: "population",
    attributeKey: "foreignBornShare",
    type: "numeric",
    legendType: "gradient",
    unit: "%",
    formatter: "percentage",
    nullLabel: "No data",
    enabledInV1: false,
  },
  // Politics
  {
    id: "municipal_winner",
    label: "Election winner",
    group: "politics",
    description: "Winning party in the latest municipal election.",
    sourceKey: "politics",
    attributeKey: "latestWinner",
    type: "categorical",
    legendType: "categories",
    nullLabel: "No election data",
    enabledInV1: false,
    citation: "Ministerio del Interior",
  },
  {
    id: "pp_vote_share",
    label: "PP vote share",
    group: "politics",
    description: "Partido Popular vote share in the latest municipal election.",
    sourceKey: "politics",
    attributeKey: "ppVoteShare",
    type: "numeric",
    legendType: "gradient",
    unit: "%",
    formatter: "percentage",
    nullLabel: "No election data",
    enabledInV1: false,
  },
  {
    id: "turnout",
    label: "Turnout",
    group: "politics",
    description: "Voter participation rate in the latest municipal election.",
    sourceKey: "politics",
    attributeKey: "turnout",
    type: "numeric",
    legendType: "gradient",
    unit: "%",
    formatter: "percentage",
    nullLabel: "No election data",
    enabledInV1: false,
  },
  // Geography
  {
    id: "corridor",
    label: "Corridor",
    group: "geography",
    description: "Functional geographic corridor or zone.",
    sourceKey: "classifications",
    attributeKey: "corridor",
    type: "categorical",
    legendType: "categories",
    nullLabel: "Unclassified",
    enabledInV1: true,
  },
  {
    id: "geography_type",
    label: "Geography type",
    group: "geography",
    description: "Terrain and landscape classification.",
    sourceKey: "classifications",
    attributeKey: "geographyType",
    type: "categorical",
    legendType: "categories",
    nullLabel: "Unclassified",
    enabledInV1: false,
  },
  // Mobility
  {
    id: "distance_to_madrid",
    label: "Distance to Madrid",
    group: "mobility",
    description: "Straight-line distance from centroid to Puerta del Sol.",
    sourceKey: "mobility",
    attributeKey: "distanceToMadridKm",
    type: "numeric",
    legendType: "gradient",
    unit: "km",
    formatter: "integer",
    nullLabel: "No data",
    enabledInV1: false,
  },
  {
    id: "mobility_type",
    label: "Mobility type",
    group: "mobility",
    description: "Primary public transport connection type.",
    sourceKey: "classifications",
    attributeKey: "mobilityType",
    type: "categorical",
    legendType: "categories",
    nullLabel: "Unclassified",
    enabledInV1: false,
  },
  // Economy
  {
    id: "avg_income",
    label: "Average income",
    group: "economy",
    description: "Average annual income per person (AEAT data).",
    sourceKey: "economy",
    attributeKey: "avgIncomeEur",
    type: "numeric",
    legendType: "gradient",
    unit: "€",
    formatter: "currency",
    nullLabel: "No income data",
    enabledInV1: false,
    citation: "AEAT estadísticas municipales",
  },
  {
    id: "unemployment_rate",
    label: "Unemployment rate",
    group: "economy",
    description: "Registered unemployment rate.",
    sourceKey: "economy",
    attributeKey: "unemploymentRate",
    type: "numeric",
    legendType: "gradient",
    unit: "%",
    formatter: "percentage",
    nullLabel: "No data",
    enabledInV1: false,
  },
  // Housing
  {
    id: "price_per_m2",
    label: "Housing price / m²",
    group: "housing",
    description: "Average sale price per square metre.",
    sourceKey: "housing",
    attributeKey: "pricePerM2",
    type: "numeric",
    legendType: "gradient",
    unit: "€/m²",
    formatter: "currency",
    nullLabel: "No price data",
    enabledInV1: false,
  },
  // Environment
  {
    id: "protected_area_share",
    label: "Protected area",
    group: "environment",
    description: "Percentage of municipal area under natural protection.",
    sourceKey: "geography",
    attributeKey: "protectedAreaShare",
    type: "numeric",
    legendType: "gradient",
    unit: "%",
    formatter: "percentage",
    nullLabel: "No data",
    enabledInV1: false,
  },
  // Game
  {
    id: "learning_difficulty",
    label: "Game difficulty",
    group: "game",
    description: "How hard this municipality is to identify in the quiz.",
    sourceKey: "derived/difficulty_scores",
    attributeKey: "difficultyLabel",
    type: "categorical",
    legendType: "categories",
    nullLabel: "Not scored yet",
    enabledInV1: true,
    citation: "Derived from area, shape, neighbour count",
  },
];

export function getLayerConfig(id: string): AtlasLayerConfig | undefined {
  return atlasLayers.find((l) => l.id === id);
}

export function getLayersByGroup(group: string): AtlasLayerConfig[] {
  return atlasLayers.filter((l) => l.group === group);
}

export function getEnabledV1Layers(): AtlasLayerConfig[] {
  return atlasLayers.filter((l) => l.enabledInV1);
}

export const LAYER_GROUP_LABELS: Record<string, string> = {
  overview: "Overview",
  demography: "Demography",
  politics: "Politics",
  geography: "Geography",
  mobility: "Mobility",
  economy: "Economy",
  housing: "Housing",
  services: "Services",
  culture: "Culture",
  environment: "Environment",
  game: "Game",
};
